# Generated by Django 3.0.6 on 2020-05-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='press_couter',
            field=models.IntegerField(default=0),
        ),
    ]
