# Generated by Django 3.0.6 on 2020-05-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_press_couter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connected_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username2', max_length=20),
            preserve_default=False,
        ),
    ]
