# Generated by Django 3.0.6 on 2020-05-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20200523_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
